// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX63qRCtKCG8wRbgD1enDSKVIkc1FlzAA',
    appId: '1:745457276869:web:ce20212578de52b1871dac',
    messagingSenderId: '745457276869',
    projectId: 'homzes-firebase',
    authDomain: 'homzes-firebase.firebaseapp.com',
    storageBucket: 'homzes-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2UJYhUOxvibVCaH8XF4tBFQM4u3Fe04',
    appId: '1:745457276869:android:bf2aa197e85e6e1e871dac',
    messagingSenderId: '745457276869',
    projectId: 'homzes-firebase',
    storageBucket: 'homzes-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvajAQ-6_bKd71N9qB8CnmYJdcew_LxQg',
    appId: '1:745457276869:ios:8943505828ce6429871dac',
    messagingSenderId: '745457276869',
    projectId: 'homzes-firebase',
    storageBucket: 'homzes-firebase.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvajAQ-6_bKd71N9qB8CnmYJdcew_LxQg',
    appId: '1:745457276869:ios:8943505828ce6429871dac',
    messagingSenderId: '745457276869',
    projectId: 'homzes-firebase',
    storageBucket: 'homzes-firebase.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX63qRCtKCG8wRbgD1enDSKVIkc1FlzAA',
    appId: '1:745457276869:web:23666517123a6a8f871dac',
    messagingSenderId: '745457276869',
    projectId: 'homzes-firebase',
    authDomain: 'homzes-firebase.firebaseapp.com',
    storageBucket: 'homzes-firebase.firebasestorage.app',
  );
}
